version: "3.7"

services:
  service-1:
    build:
      context: ./service-1
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./service-1/src:/home/node/app/src
    container_name: service-1
    expose:
      - "4000"
    ports:
      - "4000:4000"
    command: yarn start
  service-2:
    build:
      context: ./service-2
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./service-2/src:/home/node/app/src
    container_name: service-2
    expose:
      - "4001"
    ports:
      - "4001:4001"
    command: yarn start
